spring.application.name=EvilHamster
server.port=8080
server.address=0.0.0.0

bot.name=altcoins_trade_bot
bot.token=8933244482:AAE-smYkAOKmH7YH7zMt51UEWrdqm48_VBQ

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
